[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=0.18.0",
    "pydantic>=2.10.6",
    "pypdf2>=3.0.1",
    "streamlit>=1.42.1",
]
