# FROM golang:latest
FROM python:latest

WORKDIR /workspace

# COPY . .
RUN apt-get update && apt-get install -y fish
RUN pip install uv
# RUN go install github.com/air-verse/air@latest
# RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
